version: '3.8'

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    image: frontend:2.0
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    image: backend:2.0
    volumes:
      - data:/app/data
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  data:
    driver: local